### ISSUE TITLE
Suggestion: Result count

### ISSUE THREAD

**Issue by KernelForbin** [dolandrew/googli-ui#14]
Hey! Love the project. Wasn't sure how you were taking suggestions, so this seemed like perhaps the best option.

If possible: I think it would be beneficial to have a count of total results from the search. Somewhere towards the top. 

Thanks!
-KF

**Comment by dolandrew** [comment]
Hey there! Thank you for the suggestion. I agree it's a great idea. And, I think it would make the no results case a little more clear if it displayed "no results". 

I'm about to open a pull request for it, and will probably merge it soon. 

-Andrew

**Comment by dolandrew** [comment]
<img width="487" alt="Screen Shot 2020-03-12 at 8 14 51 PM" src="https://user-images.githubusercontent.com/28452598/76586575-704e2000-649e-11ea-803d-37dfaab0f8fc.png">

Implemented a simple results count above the results. Let me know what you think.
